version: '3.1'

services: n8n: image: n8nio/n8n:latest restart: always ports: - "5678:5678" environment: - N8N_HOST=https://www.google.com/search?q=automation.staqlt.com - NODE_ENV=production - WEBHOOK_URL=https://automation.staqlt.com/ volumes: - n8n_data:/home/node/.n8n

volumes: n8n_data: